export const STATUSES = [
  {
    id: 1,
    description: "Constituent request in",
    sequence_num: 1,
    status_federal_office_code: "HOSS",
    active_status: "OPEN",
    status_code: "HOSS_RECEIVED",
  },
  {
    id: 2,
    description: "HOSS verified as printed and scanned physical QR code",
    sequence_num: 2,
    status_federal_office_code: "HOSS",
    active_status: "OPEN",
    status_code: "HOSS_VERIFIED",
  },
  {
    id: 3,
    description: "AOC received flag from HOSS",
    sequence_num: 3,
    status_federal_office_code: "AOC",
    active_status: "OPEN",
    status_code: "AOC_RECEIVED",
  },
  {
    id: 4,
    description: "AOC has flown flag and added certificate",
    // OPTIONAL: date specified vs soon as possible
    sequence_num: 4,
    status_federal_office_code: "AOC",
    active_status: "OPEN",
    status_code: "AOC_FLOWN",
  },
  {
    id: 5,
    description: "Mail Services picked up flag from AOC",
    sequence_num: 5,
    status_federal_office_code: "MAIL",
    active_status: "OPEN",
    status_code: "MAIL_RECEIVED",
  },
  {
    id: 6,
    description: "Congressional Staffer received flag",
    sequence_num: 6,
    status_federal_office_code: "STAFF",
    active_status: "OPEN",
    status_code: "STAFF_RECEIVED",
  },
  {
    id: 7,
    description: "Staffer order closed (Flag ready for shipment)",
    sequence_num: 7,
    status_federal_office_code: "STAFF",
    active_status: "OPEN",
    status_code: "STAFF_CLOSED",
  },
  {
    id: 8,
    description: "Constituent notified",
    sequence_num: 8,
    status_federal_office_code: "STAFF",
    active_status: "CLOSED",
    status_code: "CONST_NOTIFIED",
  },
  {
    id: 9,
    description: "Order canceled",
    sequence_num: 9,
    status_federal_office_code: "ALL",
    active_status: "CANCELED",
    status_code: "CANCELED",
  },
];
