export const STATUSES = [
  {
    id: 1,
    description: "Constituent request in",
    sequence_num: 1,
    status_federal_office_code: "HOSS",
    tags: "STANDARD",
  },
  {
    id: 2,
    description: "HOSS verified as printed and scanned physical QR code",
    sequence_num: 2,
    status_federal_office_code: "HOSS",
    tags: "STANDARD",
  },
  {
    id: 3,
    description: "AOC received flag from HOSS",
    sequence_num: 3,
    status_federal_office_code: "AOC",
    tags: "STANDARD",
  },
  {
    id: 4,
    description: "AOC has flown flag and added certificate",
    // OPTIONAL: date specified vs soon as possible
    sequence_num: 4,
    status_federal_office_code: "AOC",
    tags: "STANDARD",
  },
  {
    id: 5,
    description: "Mail Services picked up flag from AOC",
    sequence_num: 5,
    status_federal_office_code: "MAIL",
    tags: "STANDARD",
  },
  {
    id: 6,
    description: "Congressional Staffer received flag",
    sequence_num: 6,
    status_federal_office_code: "STATE",
    tags: "STANDARD",
  },
  {
    id: 7,
    description: "Staffer order closed (Flag ready for shipment)",
    sequence_num: 7,
    status_federal_office_code: "STATE",
    tags: "STANDARD",
  },
  {
    id: 8,
    description: "Constituent notified",
    sequence_num: 8,
    status_federal_office_code: "STATE",
    tags: "STANDARD",
  },
  {
    id: 9,
    description: "Order canceled",
    sequence_num: 9,
    status_federal_office_code: "ALL",
    tags: "CANCEL",
  },
];
