# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
#  [pull_request, workflow_dispatch]
workflow_dispatch

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
     - name: checkout frontend
       uses: actions/checkout@v3
       with:
          path: main
     - name: checkout backend
       uses: actions/checkout@main
       with:
         name: codefordc/us-congress-pizza-flag-tracker
         path: backend
         
      # Runs a single command using the runners shell
     - name: Run a one-line script
       run: echo Hello, world! No bugs found yet!

      # Runs a set of commands using the runners shell
     - name: Run a multi-line script
       run: |
          pwd
          ls
